### PR TITLE
Statusline

### PR DESCRIPTION
**Pull request by karl-01**
+I have just found your tablacus explorer and I like it very much.
+It is almost the explorer I am looking for since a long time.
+What I miss, is a statusline, giving the number of files in a directory and the number of selected files.
+Is there some add-on for this? I did not find it.
+Can you please add it?
+
+Many thanks
+Karl

### CODE REVIEW

**Comment by tablacus** [comment]
You should install an add-on called "count bar".
Best regards,

**Comment by karl-01** [comment]
Thank you,

 

it works perfect!

 

All the best

Werner

 

Von: Gaku [mailto:notifications@github.com] 
Gesendet: Sonntag, 12. April 2015 16:19
An: tablacus/TablacusExplorer
Cc: karl-01
Betreff: Re: [TablacusExplorer] Statusline (#36)

 

You should install an add-on called "count bar".
Best regards,

**Comment by karl-01** [comment]
Hi Gaku,

 

I still like and use your Tablacus-Explorer.

 

Question:

How can I modify Tablacus-Explorer to show hidden- and system-files?

Which Add-on is needed?

I do not find it.

 

Thanks

Werner

 

--------------------------------------

Thank you,

 

it works perfect!

 

All the best

Werner

 

Von: Gaku [mailto:notifications@github.com] 
Gesendet: Sonntag, 12. April 2015 16:19
An: tablacus/TablacusExplorer
Cc: karl-01
Betreff: Re: [TablacusExplorer] Statusline (#36)

 

You should install an add-on called "count bar".
Best regards,

**Comment by tablacus** [comment]
# Options
Tools -> Options -> List -> General -> Show all files
image

# Add-ons
Switch hidden items
image

Regards,

**Pull request closed without merging**
